# Generated by Django 3.1.1 on 2022-02-14 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Page translation',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.page',),
        ),
    ]
