# Generated by Django 3.1.1 on 2022-02-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdescription',
            name='annualSalary_currency',
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='annualSalary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Enter annual salary', max_digits=11, verbose_name='Annual salary'),
        ),
    ]
