# Generated by Django 3.1.1 on 2022-02-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20220210_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='annualSalary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Enter annual salary in USD', max_digits=11, verbose_name='Annual salary'),
        ),
    ]
