# Generated by Django 3.1.1 on 2022-01-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='interviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewDate', models.DateField(help_text='Enter the interview date ', verbose_name='Inteview date')),
                ('interviewFile', models.CharField(help_text='Add interview file', max_length=250, verbose_name='Interview file')),
                ('interviewPerformance', models.BooleanField(default=False, help_text='Interview performance OK?', verbose_name='Interview performance')),
                ('interviewResults', models.CharField(help_text='Enter the interview results', max_length=250, verbose_name='Interview results')),
                ('location', models.CharField(help_text='Enter Location', max_length=250, verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Interview',
                'verbose_name_plural': 'Interviews',
            },
        ),
    ]
