# Generated by Django 3.1.1 on 2022-01-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0002_jobdescription_recruitment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='departament',
            field=models.CharField(help_text='Enter the departament', max_length=250, verbose_name='Departament'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='departament',
            field=models.CharField(help_text='Enter the departament', max_length=250, verbose_name='Departament'),
        ),
    ]
