# Generated by Django 3.1.1 on 2022-01-28 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0003_auto_20220128_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaName', models.CharField(help_text='Enter the area name', max_length=250, verbose_name='Area name')),
                ('areaDescription', models.CharField(help_text='Enter the area description', max_length=500, verbose_name='Area description')),
                ('areaCode', models.CharField(help_text='Enter area code', max_length=250, verbose_name='Area Code')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='departament',
            field=models.ForeignKey(help_text='Enter the departament', on_delete=django.db.models.deletion.CASCADE, to='rrhh.area', verbose_name='Departament'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='departament',
            field=models.ForeignKey(help_text='Enter the departament', on_delete=django.db.models.deletion.CASCADE, to='rrhh.area', verbose_name='Departament'),
        ),
    ]
