# Generated by Django 3.1.1 on 2022-01-31 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0004_auto_20220128_1618'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='interviews',
            new_name='Interview',
        ),
    ]
