# Generated by Django 3.1.1 on 2022-02-02 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rrhh', '0006_auto_20220202_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='createdBy',
            field=models.ForeignKey(help_text='User who created the description.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
    ]
