# Generated by Django 3.1.1 on 2022-02-02 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rrhh', '0007_auto_20220202_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='numberOfVacancies',
            field=models.PositiveIntegerField(help_text='Enter the number of vacancies', verbose_name='Number of vacancies'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='requester',
            field=models.ForeignKey(help_text='Requester who created the request.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Requester'),
        ),
    ]
