# Generated by Django 3.1.1 on 2022-02-02 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0009_auto_20220202_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='jobDescription',
            field=models.ForeignKey(blank=True, help_text='Select job description', null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.jobdescription', verbose_name='Job description'),
        ),
    ]
