# Generated by Django 3.1.1 on 2022-02-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0011_auto_20220202_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='approvalsComments',
            field=models.CharField(blank=True, help_text='Enter the comments', max_length=500, verbose_name='Approvals comments'),
        ),
    ]
