# Generated by Django 3.1.1 on 2022-02-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0012_auto_20220202_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='requisitionApproved',
            field=models.BooleanField(default=False, help_text='Requisition Approved?', verbose_name='Requisition approved?'),
        ),
    ]
