# Generated by Django 3.1.1 on 2021-11-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211006_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=False, help_text='Field to know if the product is active or not active'),
        ),
        migrations.AlterField(
            model_name='product',
            name='descritption',
            field=models.TextField(help_text='Here you must write the product description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, help_text='Price of product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='A short name, generally used in URLs.', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='Name of product, example product 1', max_length=150),
        ),
    ]
