# Generated by Django 3.1.1 on 2021-11-15 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_auto_20211111_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line_1',
            field=models.CharField(help_text='Register an address ', max_length=150),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line_2',
            field=models.CharField(help_text='Register a second address', max_length=150),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('B', 'Billing'), ('S', 'Shipping')], help_text='Allows you to choose between different types of addresses', max_length=1),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(help_text='City where the purchase is made', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='default',
            field=models.BooleanField(default=False, help_text='Allows to set default address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(help_text='City zip code', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(blank=True, help_text='Date of purchase', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(help_text='Name of the user making the purchase ', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Quantity you want to buy'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(help_text='Amount paid'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Paypal', 'Paypal')], help_text='Select payment method', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='raw_response',
            field=models.TextField(help_text='Payment gateway response'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='succesful',
            field=models.BooleanField(default=False, help_text='Successful payment?'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='Date of payment'),
        ),
    ]
