# Generated by Django 3.1.1 on 2022-01-31 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc', models.CharField(blank=True, help_text='Enter your ID number ', max_length=11, verbose_name='CC')),
                ('cellphone', models.CharField(blank=True, help_text='Enter your cell phone number ', max_length=11, verbose_name='Cellphone')),
                ('home_address', models.CharField(blank=True, help_text='Enter your home address', max_length=150, verbose_name='Home address')),
                ('Age', models.IntegerField(default=0, help_text='Enter your Age', verbose_name='Age')),
                ('user', models.OneToOneField(default=1, help_text='Enter a user name ', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
    ]
