# Generated by Django 3.1.1 on 2021-12-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='edad',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
