# Generated by Django 3.1.1 on 2021-12-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_person_edad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='address',
            new_name='home_address',
        ),
        migrations.AlterField(
            model_name='person',
            name='edad',
            field=models.IntegerField(default=0),
        ),
    ]
