# Generated by Django 3.1.1 on 2022-01-27 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_auto_20211231_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='celphone',
        ),
        migrations.RemoveField(
            model_name='person',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='person',
            name='rol',
        ),
        migrations.AddField(
            model_name='person',
            name='Age',
            field=models.IntegerField(default=0, help_text='Enter your Age', verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='person',
            name='cellphone',
            field=models.CharField(blank=True, help_text='Enter your cell phone number ', max_length=11, verbose_name='Cellphone'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cc',
            field=models.CharField(blank=True, help_text='Enter your ID number ', max_length=11, verbose_name='CC'),
        ),
        migrations.AlterField(
            model_name='person',
            name='home_address',
            field=models.CharField(blank=True, help_text='Enter your home address', max_length=150, verbose_name='Home address'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(default=1, help_text='Enter a user name ', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
